### ISSUE TITLE
install ant version

### ISSUE THREAD

**Issue by savoia-dev** [Toberumono/WRF-Runner#3]
Hi,
thanks for your great work;
When I install ant, I see this issue.

```
bash <(curl -#fsSL "https://raw.githubusercontent.com/Toberumono/Miscellaneous/master/ant/automatic_install.sh")
Available Ant version: 1.9.10
1.10.2
Current Apache-Ant version: none
Installing Apache Ant version 1.9.10
1.10.2.
--2018-02-17 17:26:39--  http://apache.mirrors.tds.net//ant/binaries/apache-ant-1.9.10%0A1.10.2-bin.tar.gz
Risoluzione di apache.mirrors.tds.net (apache.mirrors.tds.net)... 216.165.129.134
Connessione a apache.mirrors.tds.net (apache.mirrors.tds.net)|216.165.129.134|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2018-02-17 17:26:40 ERRORE 404: Not Found.
```

**Comment by Toberumono** [comment]
It would appear that my download script broke. I'll fix that when I can (likely not for a couple more days).
For now, if you are on a Mac and you used my WRF Setup Script or have Homebrew, run `brew install ant`. If you're on Linux, use apt or yum. I'm guessing that the commands would be `sudo apt-get install ant` and `sudo yum install ant`; however, I could be wrong on those two.

**Comment by savoia-dev** [comment]
thanks
I install ant package with sudo apt-get install ant
